[project]
name = "mcp-ddgs"
version = "0.1.0"
description = "Simple Model Context Protocol server for searching Duck Duck Go"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckduckgo-search>=7.4.2",
    "httpx>=0.28.1",
    "mcp[cli]>=1.2.1",
]
